version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./apps/api
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
    ports: ["4000:4000"]
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    volumes:
      - ./apps/api/uploads:/app/uploads

  web:
    build: ./apps/web
    env_file: ./.env
    depends_on: [api]
    ports: ["5173:5173"]
    command: sh -c "npm run dev -- --host"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]

volumes:
  pgdata: