version: "3.9"
services:
  api:
    build: ./apps/api
    env_file: ./.env
    ports: ["4000:4000"]
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    volumes:
      - ./apps/api/uploads:/app/uploads

  web:
    build: ./apps/web
    env_file: ./.env
    depends_on: [api]
    ports: ["5173:5173"]
    command: sh -c "npm run dev -- --host"
